<?php
// 中文语言文件
return array(
	// 通用
	'app_title' => 'Web文件管理系统',
	'ok' => '确定',
	'cancel' => '取消',
	'close' => '关闭',
	'confirm' => '确认',
	'loading' => '加载中...',

	// 登录页
	'login_title' => '登录 - Web文件管理系统',
	'login' => '登录',
	'logout' => '退出',
	'username' => '用户名',
	'password' => '密码',
	'ph_username' => '请输入用户名',
	'ph_password' => '请输入密码',
	'keep_login' => '保持登录（2个月内免登录）',
	'err_empty_fields' => '用户名和密码不能为空',
	'err_wrong_credentials' => '用户名或密码错误',

	// 顶栏
	'new_window' => '新建窗口',
	'admin' => '管理员',
	'normal_user' => '普通用户',
	'system' => '系统',
	'operation_log' => '操作日志',
	'upload_list' => '上传列表',
	'exit' => '退出',

	// 上传面板
	'upload_tasks' => '上传任务',
	'clear_completed' => '清除已完成',
	'close_panel' => '关闭面板',
	'total_tasks' => '共 {count} 个任务',
	'completed_n' => '已完成 {count}',
	'upload_failed' => '上传失败',

	// 文件列表列头
	'name' => '名称',
	'size' => '大小',
	'type' => '类型',
	'modified_date' => '修改日期',
	'actions_col' => '操作',
	'folder' => '文件夹',
	'file' => '文件',
	'folder_empty' => '此文件夹为空',
	'root_dir' => '根目录',
	'items_count' => '{count} 个项目',
	'folders_count' => '（{count} 个文件夹）',
	'files_count' => '（{count} 个文件）',

	// 工具栏
	'back' => '返回上一级',
	'detail_view' => '详细视图',
	'icon_view' => '图标视图',
	'large_view' => '大图标视图',
	'paste' => '粘贴',
	'upload' => '上传',
	'upload_files' => '上传文件',
	'new_folder' => '新建文件夹',
	'new' => '新建',
	'download_zip_dir' => '下载当前目录为ZIP包',
	'download_zip_folder' => '下载文件夹为ZIP包',
	'maximize' => '最大化',

	// 行按钮
	'download' => '下载',
	'download_zip' => '下载为ZIP',
	'delete' => '删除',

	// 右键菜单
	'enter' => '进入',
	'open_new_window' => '新窗口打开',
	'rename' => '重命名',
	'copy_zip_link' => '复制ZIP链接',
	'download_zip_pkg' => '下载为ZIP包',
	'properties' => '属性',
	'preview' => '预览',
	'copy_link' => '复制链接',
	'refresh' => '刷新',
	'copy' => '复制',
	'cut' => '剪切',
	'delete_n_items' => '删除 {count} 项',
	'download_n_zip' => '下载 {count} 项为ZIP包',
	'cut_n_items' => '剪切 {count} 项',
	'copy_n_items' => '复制 {count} 项',
	'n_items' => '{count} 项',

	// 提示消息
	'deleted' => '已删除',
	'delete_failed' => '删除失败',
	'deleted_n' => '已删除 {count} 项',
	'confirm_delete' => '确定要删除 "{name}" 吗？',
	'confirm_delete_n' => '确定要删除选中的 {count} 项吗？',
	'renamed' => '已重命名',
	'rename_failed' => '重命名失败',
	'batch_rename_unsupported' => '暂不支持批量重命名',
	'cut_n' => '已剪切 {count} 项',
	'cut_name' => '已剪切: {name}',
	'copied_n' => '已复制 {count} 项',
	'copied_name' => '已复制: {name}',
	'clipboard_empty' => '剪贴板为空',
	'pasted_n' => '已粘贴 {count} 项',
	'paste_failed' => '粘贴失败',
	'created' => '已创建',
	'create_failed' => '创建失败',
	'load_failed' => '加载失败',
	'props_failed' => '获取属性失败',
	'link_copied' => '链接已复制',
	'zip_link_copied' => 'ZIP链接已复制',
	'moved_n' => '已移动 {count} 项',
	'path_not_exist' => '路径不存在: up/{path}',
	'parse_failed' => '解析失败',
	'network_error' => '网络错误',
	'read_failed' => '读取失败: {err}',
	'preview_unsupported' => '暂不支持预览此文件类型',
	'edit' => '编辑',
	'save' => '保存',
	'saved' => '已保存',
	'save_failed' => '保存失败',

	// 属性对话框
	'file_count' => '文件数',
	'total_size' => '总大小',
	'modified_time' => '修改时间',
	'created_time' => '创建时间',
	'dimensions' => '尺寸',

	// 日志面板
	'time' => '时间',
	'user' => '用户',
	'operation' => '操作',
	'path' => '路径',
	'detail' => '详情',
	'no_logs' => '暂无日志',

	// 日志操作名称
	'log_login' => '登录',
	'log_logout' => '登出',
	'log_upload' => '上传',
	'log_download' => '下载',
	'log_del' => '删除',
	'log_ren' => '重命名',
	'log_mkdir' => '新建文件夹',
	'log_paste' => '粘贴',
	'log_copy' => '复制',
	'log_zip' => 'ZIP下载',
	'log_save' => '保存',

	// PHP 错误消息
	'err_invalid_path' => '无效路径',
	'err_create_failed' => '创建失败',
	'err_delete_protected' => '不能删除受保护的文件',
	'err_modify_protected' => '不能修改受保护的文件',
	'err_rename_failed' => '重命名失败',
	'err_paste_failed' => '粘贴失败',
	'err_upload_protected' => '不能上传文件到受保护的目录',
	'err_zip_protected' => '不能打包受保护的文件',
	'err_unknown' => '未知操作',
	'err_permission' => '权限不足：仅管理员可操作',

	// 语言切换
	'language' => '语言',
	'lang_en' => 'English',
	'lang_zh' => '中文',
);
