<?php
// English language file (default)
return array(
	// General
	'app_title' => 'Web File Manager',
	'ok' => 'OK',
	'cancel' => 'Cancel',
	'close' => 'Close',
	'confirm' => 'Confirm',
	'loading' => 'Loading...',

	// Login page
	'login_title' => 'Login - Web File Manager',
	'login' => 'Login',
	'logout' => 'Logout',
	'username' => 'Username',
	'password' => 'Password',
	'ph_username' => 'Enter username',
	'ph_password' => 'Enter password',
	'keep_login' => 'Keep me logged in (2 months)',
	'err_empty_fields' => 'Username and password cannot be empty',
	'err_wrong_credentials' => 'Wrong username or password',

	// Top bar
	'new_window' => 'New Window',
	'admin' => 'Admin',
	'normal_user' => 'User',
	'system' => 'System',
	'operation_log' => 'Operation Log',
	'upload_list' => 'Upload List',
	'exit' => 'Exit',

	// Upload panel
	'upload_tasks' => 'Upload Tasks',
	'clear_completed' => 'Clear completed',
	'close_panel' => 'Close panel',
	'total_tasks' => 'Total {count} tasks',
	'completed_n' => 'Completed {count}',
	'upload_failed' => 'Upload failed',

	// File list columns
	'name' => 'Name',
	'size' => 'Size',
	'type' => 'Type',
	'modified_date' => 'Modified',
	'actions_col' => 'Actions',
	'folder' => 'Folder',
	'file' => 'File',
	'folder_empty' => 'This folder is empty',
	'root_dir' => 'Root',
	'items_count' => '{count} items',
	'folders_count' => '({count} folders)',
	'files_count' => '({count} files)',

	// Toolbar
	'back' => 'Back to parent',
	'detail_view' => 'Detail view',
	'icon_view' => 'Icon view',
	'large_view' => 'Large icon view',
	'paste' => 'Paste',
	'upload' => 'Upload',
	'upload_files' => 'Upload files',
	'new_folder' => 'New Folder',
	'new' => 'New',
	'download_zip_dir' => 'Download current directory as ZIP',
	'download_zip_folder' => 'Download folder as ZIP',
	'maximize' => 'Maximize',

	// Row buttons
	'download' => 'Download',
	'download_zip' => 'Download as ZIP',
	'delete' => 'Delete',

	// Context menu
	'enter' => 'Enter',
	'open_new_window' => 'Open in new window',
	'rename' => 'Rename',
	'copy_zip_link' => 'Copy ZIP link',
	'download_zip_pkg' => 'Download as ZIP',
	'properties' => 'Properties',
	'preview' => 'Preview',
	'copy_link' => 'Copy link',
	'refresh' => 'Refresh',
	'copy' => 'Copy',
	'cut' => 'Cut',
	'delete_n_items' => 'Delete {count} items',
	'download_n_zip' => 'Download {count} items as ZIP',
	'cut_n_items' => 'Cut {count} items',
	'copy_n_items' => 'Copy {count} items',
	'n_items' => '{count} items',

	// Toast messages
	'deleted' => 'Deleted',
	'delete_failed' => 'Delete failed',
	'deleted_n' => 'Deleted {count} items',
	'confirm_delete' => 'Are you sure you want to delete "{name}"?',
	'confirm_delete_n' => 'Are you sure you want to delete {count} selected items?',
	'renamed' => 'Renamed',
	'rename_failed' => 'Rename failed',
	'batch_rename_unsupported' => 'Batch rename not supported',
	'cut_n' => 'Cut {count} items',
	'cut_name' => 'Cut: {name}',
	'copied_n' => 'Copied {count} items',
	'copied_name' => 'Copied: {name}',
	'clipboard_empty' => 'Clipboard is empty',
	'pasted_n' => 'Pasted {count} items',
	'paste_failed' => 'Paste failed',
	'created' => 'Created',
	'create_failed' => 'Create failed',
	'load_failed' => 'Load failed',
	'props_failed' => 'Failed to get properties',
	'link_copied' => 'Link copied',
	'zip_link_copied' => 'ZIP link copied',
	'moved_n' => 'Moved {count} items',
	'path_not_exist' => 'Path does not exist: up/{path}',
	'parse_failed' => 'Parse failed',
	'network_error' => 'Network error',
	'read_failed' => 'Read failed: {err}',
	'preview_unsupported' => 'This file type cannot be previewed',
	'edit' => 'Edit',
	'save' => 'Save',
	'saved' => 'Saved',
	'save_failed' => 'Save failed',

	// Properties dialog
	'file_count' => 'File count',
	'total_size' => 'Total size',
	'modified_time' => 'Modified',
	'created_time' => 'Created',
	'dimensions' => 'Dimensions',

	// Log panel
	'time' => 'Time',
	'user' => 'User',
	'operation' => 'Operation',
	'path' => 'Path',
	'detail' => 'Detail',
	'no_logs' => 'No logs yet',

	// Log action names
	'log_login' => 'Login',
	'log_logout' => 'Logout',
	'log_upload' => 'Upload',
	'log_download' => 'Download',
	'log_del' => 'Delete',
	'log_ren' => 'Rename',
	'log_mkdir' => 'New Folder',
	'log_paste' => 'Paste',
	'log_copy' => 'Copy',
	'log_zip' => 'ZIP Download',
	'log_save' => 'Save',

	// PHP error messages
	'err_invalid_path' => 'Invalid path',
	'err_create_failed' => 'Create failed',
	'err_delete_protected' => 'Cannot delete protected file',
	'err_modify_protected' => 'Cannot modify protected file',
	'err_rename_failed' => 'Rename failed',
	'err_paste_failed' => 'Paste failed',
	'err_upload_protected' => 'Cannot upload to protected directory',
	'err_zip_protected' => 'Cannot zip protected file',
	'err_unknown' => 'Unknown operation',
	'err_permission' => 'Permission denied: admin only',

	// Language switcher
	'language' => 'Language',
	'lang_en' => 'English',
	'lang_zh' => '中文',
);
